# name: Tests

# on: push

# jobs:
#   tests:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Remove Package-lock file
#         run: rm package-lock.json
#       - name: Install Modules
#         run: npm i
#       - name: Run Build
#         run: npm run build
#       - name: Run Tests
#         run: npm run test
